### ISSUE TITLE
Don't package EXE that you can build yourself

### ISSUE THREAD

**Issue by MaximRouiller** [microsoft/AzureAutomaticGradingEngine#13]
## Issue

The file [`AzureAutomaticGradingEngineFunctionApp/AzureGraderTestProject.exe`](https://github.com/microsoft/AzureAutomaticGradingEngine/blob/main/AzureAutomaticGradingEngineFunctionApp/AzureGraderTestProject.exe) should not be used directly.

We are compiling the executable ourselves which means we can simply refer to the code we need rather than copy/pasting an EXE. If we need to use the compiled output from one program in another, we are better publishing NuGet packages and using that instead. 

Using an EXE directly can yield to many issues including security one. Which version is it? Is it the app we meant to use?

## Recommendation

Call the necessary code directly, don't invoke EXE files unless no other choices are possible.

**Comment by wongcyrus** [comment]
There are 3 reasons to build exe.
1. I ran into a technical issue for running NUnit concurrently in Azure function.
https://github.com/microsoft/AzureAutomaticGradingEngine/pull/6
I cannot find other way to solve it.

2. I need to provide a way to let students check their mark themselves and exe is simple for them.

3. Add and change Unit test by changing Azure table without the need to redeployment. Logic is set the exe download URL, download it, then run.

In fact assignment is flexible and hard to put in Nutget as I suppose let teacher change it to prevent students getting answer from other institutions.

**Comment by wongcyrus** [comment]
New repo for grader.
https://github.com/microsoft/AzureAutomaticGradingEngine_Assignments

**Comment by leestott** [comment]
@MaximRouiller  Any suggestion and neater way of doing this?
