### ISSUE TITLE
Move XML file generating code directly where it's needed

### ISSUE THREAD

**Issue by MaximRouiller** [microsoft/AzureAutomaticGradingEngine#15]
## Issue

The [Console Runner](https://github.com/microsoft/AzureAutomaticGradingEngine/blob/main/AzureGraderConsoleRunner/Program.cs#L35) is already generating the XML then saving it to disk. We can save a step and never even save it. Just use the output of the XML as a string and save it directly in blob storage if needed.

## Recommendation

[Convert the XML node to `string`](https://stackoverflow.com/a/6442267) and use the output directly rather than using files.

**Comment by leestott** [comment]
Repo split and readme updated to reflect engine and classroom example
